# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-monitor
  template:
    metadata:
      labels:
        app: health-monitor
    spec:
      serviceAccountName: health-monitor-sa
      containers:
        - name: health-monitor
          image: sre-health-monitor
          imagePullPolicy: IfNotPresent