apiVersion: v1
kind: ServiceAccount
metadata:
  name: health-monitor-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: health-monitor-role
rules:
  # Existing rules for pods and nodes
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch", "delete", "update"]
  
  # Add the following rules for leases
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "create", "update", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: health-monitor-rolebinding
subjects:
  - kind: ServiceAccount
    name: health-monitor-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: health-monitor-role
  apiGroup: rbac.authorization.k8s.io