apiVersion: v1
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-master.monitoring.svc.cluster.local:9200"]
        index => "logstash-%{+YYYY.MM.dd}"
      }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"logstash.conf":"input {\n  beats {\n    port =\u003e 5044\n  }\n}\noutput {\n  elasticsearch {\n    hosts =\u003e [\"http://elasticsearch-master.monitoring.svc.cluster.local:9200\"]\n    index =\u003e \"logstash-%{+YYYY.MM.dd}\"\n  }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{"meta.helm.sh/release-name":"logstash","meta.helm.sh/release-namespace":"monitoring"},"creationTimestamp":"2024-09-20T23:29:48Z","labels":{"app":"logstash-logstash","app.kubernetes.io/managed-by":"Helm","chart":"logstash","heritage":"Helm","release":"logstash"},"name":"logstash-logstash-pipeline","namespace":"monitoring","resourceVersion":"86411","uid":"8f59de38-810f-468d-acd8-e3ed65b21075"}}
    meta.helm.sh/release-name: logstash
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2024-09-20T23:29:48Z"
  labels:
    app: logstash-logstash
    app.kubernetes.io/managed-by: Helm
    chart: logstash
    heritage: Helm
    release: logstash
  name: logstash-logstash-pipeline
  namespace: monitoring
  resourceVersion: "86829"
  uid: 8f59de38-810f-468d-acd8-e3ed65b21075
